### ISSUE TITLE
Cannot install on CentOS7

### ISSUE THREAD

**Issue by rubenv** [FoundationDB/sql-layer#1583]
I'm attempting to install the SQL layer on a clean CentOS7. I've installed `foundationdb-clients-3.0.4-1.el7.x86_64.rpm` and `foundationdb-server-3.0.4-1.el7.x86_64.rpm` first.

When I then try to install `fdb-sql-layer-2.0.2-1.el6.noarch.rpm`, I get:
```
warning: /opt/packages/fdb-sql-layer-2.0.2-1.el6.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID 7d5a34fc: NOKEY
        file /etc/foundationdb from install of fdb-sql-layer-2.0.2-1.el6.noarch conflicts with file from package foundationdb-clients-3.0.4-1.el7.x86_64
```

**Comment by nathanlws** [comment]
SQL Layer 2.0.3 is now out, which includes RHEL/CentOS 7 packages:
https://foundationdb.com/get#sql-rhel

Let us know if you hit any other snags!
