### ISSUE TITLE
bigint on multicolumn primary key caused wrong check error on select

### ISSUE THREAD

**Issue by RexHell** [FoundationDB/sql-layer#1660]
SQL Layer version: 2.1.0 +3d3c852
Create a table with
```
CREATE TABLE test_table (
  Id1 bigint NOT NULL,
  Id2 int NOT NULL,
  PRIMARY KEY (Id1, Id2)
);
```
and do a select
```
SELECT * FROM test_table WHERE Id1 = 20 AND Id2 = 1;
```

An error will occur
```
ERROR: required underlying INT_64 but was INT_32
```

But if there is no Id2 column, it works just fine.

**Comment by nathanlws** [comment]
Thanks for the report!

You've found a case where our internal index cursor checking isn't handling types correctly.

Should be a fairly easy fix. We'll reference this issue from the PR and then it will roll out in the next release in a few weeks.

**Comment by nathanlws** [comment]
To close the loop on this, a new release of SQL Layer (2.1.1) is out today and includes a fix for this issue.
